### ISSUE TITLE
Input hightlight broken

### ISSUE THREAD

**Issue by PandaKewt** [ilham25/dotfiles-openbox#1]
The input highlight is broken in obconf, also some icon in notification like discord is broken

**Comment by PandaKewt** [comment]
my bad, sr :((

**Comment by ilham25** [comment]
can you provide some screenshots?

**Comment by PandaKewt** [comment]
![image](https://user-images.githubusercontent.com/34622654/143731342-2bef8942-8dac-40cb-9227-1a02655ed286.png)
This is screenshot of my screen when I highlight addressbar, it should have something like green highlight but non of them show on my screen (my eng is bad sr). Also I don't have archlinux on bare-metal to test because my laptop broken when I first comment :')

**Comment by ilham25** [comment]
![image](https://user-images.githubusercontent.com/59368169/143763064-0eceac06-5d39-4669-99ca-77ac6c11312d.png)

It should be fixed right now, you can pull and then copy .themes directory to your home dir
