### ISSUE TITLE
[ISSUE] Icons don't show.

### ISSUE THREAD

**Issue by linuxmobile** [ilham25/dotfiles-openbox#2]
I follow the dotfiles tutorial, but icons never show. 
![2021-11-24-041654_1366x768_scrot](https://user-images.githubusercontent.com/10554636/143174149-0b2be540-177d-4b0e-85b2-dcccca37f00e.png)
![2021-11-24-041702_1366x768_scrot](https://user-images.githubusercontent.com/10554636/143174155-fd0a22e2-3371-484b-bc00-ac82bf6242b4.png)

**Comment by ilham25** [comment]
what distro are you using now?

also, are you run the command 1 per line in icons section?

**Comment by linuxmobile** [comment]
> what distro are you using now?
> 
> also, are you run the command 1 per line in icons section?

I'm using archlinux. 

And I'm following this:

```
cd ~/.icons/

tar -Jxvf oomox-aesthetic-light.tar.xz && tar -Jxvf oomox-aesthetic-dark.tar.xz

sudo cp -r {oomox-aesthetic-light,oomox-aesthetic-dark} /usr/share/icons/

rm -r ~/.icons/{oomox-aesthetic-light,oomox-aesthetic-dark,*.tar.xz} # Delete unnecessary files
```

**Comment by ilham25** [comment]
I have no vm right now for testing it, but you can do this to fix it :
1. copy .icons dir in my dotfiles to your home .icons
2. then extract oomox-aesthetic-light.tar.xz and oomox-aesthetic-light.tar.xz
3. copy those extracted directory to /usr/share/icons

logout and login again

**Comment by linuxmobile** [comment]
> o vm right now for testing it, but you can do this to fix it :

Yes. Manually it work! Thx u
