### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wizhel** [ilham25/dotfiles-openbox#5]
**Describe the bug**
App tabnya tidak sinkron dengan taskbarny/themeny

**Screenshots**
![2022-06-21-133413_1366x768_scrot](https://user-images.githubusercontent.com/105490719/174732434-6bc74c25-e3dc-4f19-9600-c27bc0d86811.png)

**Comment by wizhel** [comment]
ini baru di install ulang, smua langkah2ny udh diikutin dgn benar tp tetap kyk gini

**Comment by ilham25** [comment]
Itu kalo gonta ganti light/dark ttp ga sinkron ya?

Sorry bang skrg lagi pake DE jadi gabisa tes langsung

**Comment by wizhel** [comment]
> Itu kalo gonta ganti light/dark ttp ga sinkron ya?

Iya, title barnya ttp warna putih

**Comment by ilham25** [comment]
> > Itu kalo gonta ganti light/dark ttp ga sinkron ya?
> 
> Iya, title barnya ttp warna putih

Coba jalanin `echo $DESKTOP_SESSION` di terminal dan ss bang

**Comment by ilham25** [comment]
> > Itu kalo gonta ganti light/dark ttp ga sinkron ya?
> 
> Iya, title barnya ttp warna putih

sip bang, spt nya udh ketemu dimana masalahnya dan udh aku fix. Boleh dicoba lagi pull commit yg latest, trs tinggal copas directory .config ke home, dan coba gonta ganti ke light/dark. Ditunggu report nya

**Comment by ilham25** [comment]
Fix : $DESKTOP_SESSION issue in startup script
