### ISSUE TITLE
Custom Keybinding

### ISSUE THREAD

**Issue by me-abhishekpal** [ilham25/dotfiles-openbox#6]
Hi,

I was wondering how are you managing your keybindings?
How can I change one keybinding, for example, I want to change the rofi from mod+r to mod+space ?

**Comment by ilham25** [comment]
hey sorry for the late response, you can change it in ```~/.config/openbox/rc.xml```

```xml
360 <keybind key="W-r">
361      <action name="Execute">
362         <command>bash -c ~/.config/rofi/scripts/appsmenu.sh</command>
363      </action>
364 </keybind>
```

here in line 360 you can change it to ```W-space```

```xml
360 <keybind key="W-space">
361      <action name="Execute">
362         <command>bash -c ~/.config/rofi/scripts/appsmenu.sh</command>
363      </action>
364 </keybind>
```
