### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wizhel** [ilham25/dotfiles-openbox#7]
**Describe the bug**
Ini bug yg kmrn, tab nggk sinkron ama settingan

**Screenshots**
![16577862225323421244762925834244](https://user-images.githubusercontent.com/105490719/178934538-35a6bf8f-dbe1-4c1d-9e8a-943bcaeb9a68.jpg)

**Desktop (please complete the following information):**
 - OS: Artix Linux

**Additional context**
Maaf ngepost 2x, kmrn lg sibuk nugas. Yg ini udh make yg latest repo ini

**Comment by ilham25** [comment]
bisa kirim hasil command di terminal ```echo $DESKTOP_SESSION``` nya bang?

**Comment by wizhel** [comment]
![1658041511680829114232025603212](https://user-images.githubusercontent.com/105490719/179387834-c663a8f0-e06b-4ff4-aa3f-8374937a4acd.jpg)
Nggk ada yg keluar

**Comment by ilham25** [comment]
oke bang, desktop session check nya udah aku remove, sekarang coba pull latest lagi dan cukup copas directory .config

habis itu coba gonta ganti theme nya, harusnya udah sync sekarang

**Comment by wizhel** [comment]
Tq bg, skrg udh fix
