### ISSUE TITLE
[BUG] Apps menu not opening

### ISSUE THREAD

**Issue by rubbean** [ilham25/dotfiles-openbox#9]
**Describe the bug**
Basically, whenever I click the app applications menu, it doesnt show the menu on the right side of my screen instead it does nothing.
I've followed the instructions as closely as possible. The screenshot menu doesnt show either, I'm getting no errors so I've got no idea where to start, also the corners of the rightclick menu dont work properly

**Screenshots**
![2022-10-15-194243_1920x1080_scrot](https://user-images.githubusercontent.com/93204910/196000591-fa6de55f-1542-41c8-a67f-83a63a5a779a.png)
![2022-10-15-194343_1920x1080_scrot](https://user-images.githubusercontent.com/93204910/196000668-5d2f4d45-257f-4de1-b76a-20552c1b73a2.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by ilham25** [comment]
thanks for reporting the issue

you can try to check if the rofi version is above 1.7 by running `rofi -v` in your terminal. if it's not, you should update it because it doesn't work below that version

**Comment by rubbean** [comment]
> thanks for reporting the issue
> 
> you can try to check if the rofi version is above 1.7 by running `rofi -v` in your terminal. if it's not, you should update it because it doesn't work below that version

hi, sorry for the late answer, i'm running rofi 1.7.5 but i've also tried rofi 1.7.0 - 1.7.4

**Comment by ilham25** [comment]
maybe you can try run the launcher script directly `bash -c ~/.config/rofi/scripts/appsmenu.sh` and provide the logs here

**Comment by ilham25** [comment]
> > thanks for reporting the issue
> > you can try to check if the rofi version is above 1.7 by running `rofi -v` in your terminal. if it's not, you should update it because it doesn't work below that version
> 
> hi, sorry for the late answer, i'm running rofi 1.7.5 but i've also tried rofi 1.7.0 - 1.7.4

maybe you can try to run the launcher script directly `bash -c '~/.config/rofi/scripts/appsmenu.sh'` and provide the logs here

**Comment by rubbean** [comment]
hi, it seems to be me just being incompetent and not setting my default locale correctly, this causes rofi to break. Sorry for any inconvenience this caused.
